In [1]:
##Numpy Array

In [4]:
my_list=[1,2,3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.09735686, 0.8646268 , 0.33917943, 0.46207702, 0.10238686])

In [17]:
np.random.randn(2)

array([ 0.07386635, -0.93186583])

In [18]:
np.random.randn(4,4)

array([[-0.56919041,  0.57817151,  0.00365289,  2.37190651],
       [-0.00373197,  0.56873667, -0.33962286,  0.2219488 ],
       [ 0.36324177, -0.05804678,  1.47457802,  0.39573969],
       [ 1.86631105,  0.60960997,  0.01702306, -0.13918952]])

In [19]:
np.random.randint(1,100)

1

In [20]:
np.random.randint(1,100,10)

array([29, 82, 77, 50, 31, 32, 38,  8, 83, 91])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr= np.random.randint(0,50,10)

In [25]:
ranarr

array([20, 33, 41,  6, 30, 23, 21, 38, 38,  4])

In [26]:
ranarr.max()

41

In [27]:
ranarr.min()

4

In [28]:
ranarr.argmax()

2

In [29]:
ranarr.argmin()

9

In [31]:
ranarr.dtype

dtype('int32')

In [34]:
from numpy.random import randint

In [38]:
randint(2,10)

4